-- serial vs identity
------

create table users1 (
	"user_id" serial primary key,
	"username" varchar
)


create table users2 (
	"user_id" integer generated by default as identity primary key,
	"username" varchar
)

-- no se puede crear id secuales si no es por defecto, debe ser por defecto
create table users3 (
	"user_id" integer generated always as identity primary key,
	"username" varchar
)

create table users4 (
	"user_id" integer generated always as identity primary key (start with 100 increment by 2),
	"username" varchar
)

create table users4 (
	"user_id" integer generated always as identity (start with 100 increment by 2),
	"username" varchar
)


-- llave primaria  compuesta
------
create table userDual (
	id1 int,
	id2 int,
	primary key(id1,id2)
)


---------
-- uuids