-- serial vs identity
------

create table users1 (
	"user_id" serial primary key,
	"username" varchar
)


create table users2 (
	"user_id" integer generated by default as identity primary key,
	"username" varchar
)

-- no se puede crear id secuales si no es por defecto, debe ser por defecto
create table users3 (
	"user_id" integer generated always as identity primary key,
	"username" varchar
)

create table users4 (
	"user_id" integer generated always as identity primary key (start with 100 increment by 2),
	"username" varchar
)

create table users4 (
	"user_id" integer generated always as identity (start with 100 increment by 2),
	"username" varchar
)


-- llave primaria  compuesta
------
create table userDual (
	id1 int,
	id2 int,
	primary key(id1,id2)
)


-- uuids
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP EXTENSION "uuid-ossp";
select   gen_random_uuid(), uuid_generate_v4()

CREATE TABLE public.users5 (
	user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
	username varchar NULL,
	CONSTRAINT users5_pkey PRIMARY KEY (user_id)
);


--- secuencias
create SEQUENCE user_sequence;
drop SEQUENCE user_sequence;
select currval('user_sequence') as valor_anterior_secuencia,  
	   nextval('user_sequence') as secuencia, 
	   currval('user_sequence') as valor_actual_secuencia;

create table users8(
	user_id integer primary key default nextval('user_sequence'),
	username varchar
) 


